eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/

spring:
  application:
    name: auth-service
  profiles:
    include: secret

server:
  port: 8803


jwt:
  pvt-key-file-name: RSA.key
  pub-key-file-name: RSA.pub