eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/


spring:
  application:
    name: auth-service
  profiles:
    include: secret
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        register-output:
          destination: register
          content-type: application/json

server:
  port: 8803

#写入你的小程序信息
wx:
  miniapp:
    appid:  #微信小程序的appid
    secret: #微信小程序的Secret
    msgDataFormat: JSON

jwt:
  pvt-key-file-name: RSA.key
  pub-key-file-name: RSA.pub
  duration: 1D  #JWT 1天过期


