server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/
spring:
  application:
    name: api-gateway
zuul:
  routes:
    #auth-service
    auth:
      path: /auth/**
      serviceId: auth-service
      strip-prefix: false
      #过滤hearder的黑名单，默认为 sensitiveHeaders：Cookie，Set-Cookie，Authorization
      #手动把它设置为空，否则包含JWT信息的Authorization头无法传递到下游服务
      sensitiveHeaders:
    #goods-service
    goods:
      path: /goods/**
      serviceId: goods-service
      strip-prefix: false
      sensitiveHeaders:
    index:
      path: /index/**
      serviceId: goods-service
      strip-prefix: false
      sensitiveHeaders:
    catalog:
      path: /catalog/**
      serviceId: goods-service
      strip-prefix: false
      sensitiveHeaders:
    search:
      path: /search/**
      serviceId: goods-service
      strip-prefix: false
      sensitiveHeaders:
    collect:
      path: /collect/**
      serviceId: goods-service
      strip-prefix: false
      sensitiveHeaders:
    comment:
      path: /comment/**
      serviceId: goods-service
      strip-prefix: false
      sensitiveHeaders:
    region:
      path: /region/**
      serviceId: goods-service
      strip-prefix: false
      sensitiveHeaders:
    category:
      path: /category/**
      serviceId: goods-service
      strip-prefix: false
      sensitiveHeaders:
    #chat
    chat:
      path: /chat/**
      serviceId: im-service
      strip-prefix: false
      sensitiveHeaders:




