server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/
spring:
  application:
    name: api-gateway
zuul:
  ribbon:
    ReadTimeout: 60000  #超时时间
    ConnectTimeout: 60000
  routes:

    #auth-service
    auth:
      path: /auth/**
      serviceId: auth-service
      strip-prefix: false
      sensitiveHeaders: #需要手动把它设置为空，否则包含JWT信息的Authorization头无法传递到下游服务

    #chat
    chat:
      path: /chat/**
      serviceId: im-service
      strip-prefix: false
      sensitiveHeaders:

    #goods-service
    goods:
      path: /goods/**
      serviceId: goods-service
      strip-prefix: false
      sensitiveHeaders:
    index:
      path: /index/**
      serviceId: goods-service
      strip-prefix: false
      sensitiveHeaders:
    catalog:
      path: /catalog/**
      serviceId: goods-service
      strip-prefix: false
      sensitiveHeaders:
    search:
      path: /search/**
      serviceId: goods-service
      strip-prefix: false
      sensitiveHeaders:
    post:
      path: /post/**
      serviceId: goods-service
      strip-prefix: false
      sensitiveHeaders:
    goodsUser:
      path: /goodsUser/**
      serviceId: goods-service
      strip-prefix: false
      sensitiveHeaders:



