spring:
  application:
    name: goods-service
  datasource:
    url: jdbc:mysql://localhost:3306/goods_service
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8804

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.web: info
    io.github.nnkwrik.goodsservice: debug
jwt:
  pub-key-file-name: RSA.pub