eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/
#  instance:
#    hostname: clientName


spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        register-input:
          destination: register
          group: registerGroup


server:
  port: 8802